<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        $categoryMap = DB::table('material_categories')->pluck('id', 'code')->toArray();
        $plantIds = DB::table('plants')->pluck('id')->toArray();
        $now = now()->toDateTimeString();

        // Material templates keyed by category code
        $templates = [
            'CAT-BRG' => [
                ['desc' => 'Deep Groove Ball Bearing 6200',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6201',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6202',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6203',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6204',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6205',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6206',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6207',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Deep Groove Ball Bearing 6208',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A1'],
                ['desc' => 'Cylindrical Roller Bearing NJ205', 'uom' => 'PCS', 'min' => 3, 'max' => 30, 'loc' => 'RACK-A2'],
                ['desc' => 'Cylindrical Roller Bearing NJ210', 'uom' => 'PCS', 'min' => 3, 'max' => 30, 'loc' => 'RACK-A2'],
                ['desc' => 'Taper Roller Bearing 30205',     'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-A2'],
                ['desc' => 'Taper Roller Bearing 30208',     'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-A2'],
                ['desc' => 'Angular Contact Ball Bearing 7205', 'uom' => 'PCS', 'min' => 2, 'max' => 20, 'loc' => 'RACK-A3'],
                ['desc' => 'Spherical Roller Bearing 22205', 'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-A3'],
                ['desc' => 'Thrust Ball Bearing 51205',      'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-A3'],
                ['desc' => 'Needle Roller Bearing HK2520',   'uom' => 'PCS', 'min' => 5,   'max' => 40,  'loc' => 'RACK-A3'],
                ['desc' => 'Pillow Block Bearing UCP205',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-A4'],
                ['desc' => 'Pillow Block Bearing UCP206',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-A4'],
                ['desc' => 'Flange Bearing UCF205',          'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-A4'],
                ['desc' => 'Linear Bearing LM8UU',           'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-A4'],
                ['desc' => 'Bearing Housing SNL 505',        'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-A5'],
                ['desc' => 'Split Plummer Block Bearing SN505', 'uom' => 'PCS', 'min' => 2, 'max' => 20, 'loc' => 'RACK-A5'],
                ['desc' => 'Self-Aligning Ball Bearing 1205', 'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-A5'],
                ['desc' => 'Bearing SKF 6305-2RS',           'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A5'],
                ['desc' => 'Bearing SKF 6306-2RS',           'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A5'],
                ['desc' => 'Bearing NTN 6207LLU',            'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A6'],
                ['desc' => 'Bearing FAG 6208-2RSR',          'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-A6'],
                ['desc' => 'Bearing NSK 6309DDU',            'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-A6'],
                ['desc' => 'Slewing Ring Bearing 230.20.0700', 'uom' => 'PCS', 'min' => 1, 'max' => 5,  'loc' => 'RACK-A7'],
            ],
            'CAT-FST' => [
                ['desc' => 'Hex Bolt M6 x 20 SS316',         'uom' => 'PCS', 'min' => 100, 'max' => 1000, 'loc' => 'RACK-B1'],
                ['desc' => 'Hex Bolt M8 x 25 SS316',         'uom' => 'PCS', 'min' => 100, 'max' => 1000, 'loc' => 'RACK-B1'],
                ['desc' => 'Hex Bolt M10 x 30 SS316',        'uom' => 'PCS', 'min' => 100, 'max' => 1000, 'loc' => 'RACK-B1'],
                ['desc' => 'Hex Bolt M12 x 40 SS316',        'uom' => 'PCS', 'min' => 100, 'max' => 1000, 'loc' => 'RACK-B1'],
                ['desc' => 'Hex Bolt M16 x 50 SS316',        'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-B1'],
                ['desc' => 'Hex Bolt M20 x 60 SS316',        'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-B1'],
                ['desc' => 'Stud Bolt M16 x 100',            'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-B2'],
                ['desc' => 'Stud Bolt M20 x 120',            'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-B2'],
                ['desc' => 'Stud Bolt M24 x 150',            'uom' => 'PCS', 'min' => 30,  'max' => 300,  'loc' => 'RACK-B2'],
                ['desc' => 'Hex Nut M6 SS316',               'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B2'],
                ['desc' => 'Hex Nut M8 SS316',               'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B2'],
                ['desc' => 'Hex Nut M10 SS316',              'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B2'],
                ['desc' => 'Hex Nut M12 SS316',              'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B2'],
                ['desc' => 'Lock Washer M10',                 'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B3'],
                ['desc' => 'Lock Washer M12',                 'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B3'],
                ['desc' => 'Flat Washer M10 SS316',          'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B3'],
                ['desc' => 'Flat Washer M12 SS316',          'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B3'],
                ['desc' => 'Spring Washer M10',               'uom' => 'PCS', 'min' => 200, 'max' => 2000, 'loc' => 'RACK-B3'],
                ['desc' => 'U-Bolt 1/2 inch',                 'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-B3'],
                ['desc' => 'U-Bolt 3/4 inch',                 'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-B3'],
                ['desc' => 'Anchor Bolt M12 x 150',          'uom' => 'PCS', 'min' => 30,  'max' => 300,  'loc' => 'RACK-B4'],
                ['desc' => 'Anchor Bolt M16 x 200',          'uom' => 'PCS', 'min' => 30,  'max' => 300,  'loc' => 'RACK-B4'],
                ['desc' => 'Self-Tapping Screw 4x25',        'uom' => 'BOX', 'min' => 5,   'max' => 50,   'loc' => 'RACK-B4'],
                ['desc' => 'Machine Screw M5 x 16',          'uom' => 'BOX', 'min' => 5,   'max' => 50,   'loc' => 'RACK-B4'],
                ['desc' => 'Allen Key Bolt M8 x 20',         'uom' => 'PCS', 'min' => 100, 'max' => 1000, 'loc' => 'RACK-B4'],
            ],
            'CAT-ELC' => [
                ['desc' => 'MCB 1P 6A Schneider',            'uom' => 'PCS', 'min' => 5,   'max' => 50,   'loc' => 'RACK-C1'],
                ['desc' => 'MCB 1P 10A Schneider',           'uom' => 'PCS', 'min' => 5,   'max' => 50,   'loc' => 'RACK-C1'],
                ['desc' => 'MCB 1P 16A Schneider',           'uom' => 'PCS', 'min' => 5,   'max' => 50,   'loc' => 'RACK-C1'],
                ['desc' => 'MCB 3P 20A Schneider',           'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C1'],
                ['desc' => 'MCB 3P 32A Schneider',           'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C1'],
                ['desc' => 'MCCB 3P 100A Schneider',        'uom' => 'PCS', 'min' => 2,   'max' => 20,   'loc' => 'RACK-C1'],
                ['desc' => 'Contactor LC1D09 9A Schneider', 'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C2'],
                ['desc' => 'Contactor LC1D25 25A Schneider', 'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C2'],
                ['desc' => 'Thermal Overload Relay LRD',    'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C2'],
                ['desc' => 'Push Button Green 22mm',         'uom' => 'PCS', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C2'],
                ['desc' => 'Push Button Red 22mm',           'uom' => 'PCS', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C2'],
                ['desc' => 'Pilot Lamp 22mm Green 220V',    'uom' => 'PCS', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C2'],
                ['desc' => 'Pilot Lamp 22mm Red 220V',      'uom' => 'PCS', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C2'],
                ['desc' => 'Selector Switch 2 Position',    'uom' => 'PCS', 'min' => 5,   'max' => 50,   'loc' => 'RACK-C3'],
                ['desc' => 'Selector Switch 3 Position',    'uom' => 'PCS', 'min' => 5,   'max' => 50,   'loc' => 'RACK-C3'],
                ['desc' => 'Terminal Block DIN 2.5mm2',     'uom' => 'PCS', 'min' => 100, 'max' => 1000, 'loc' => 'RACK-C3'],
                ['desc' => 'Terminal Block DIN 6mm2',       'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-C3'],
                ['desc' => 'DIN Rail 35mm x 1000mm',        'uom' => 'BTG', 'min' => 5,   'max' => 50,   'loc' => 'RACK-C3'],
                ['desc' => 'Cable Duct 25x25mm PVC',        'uom' => 'BTG', 'min' => 20,  'max' => 200,  'loc' => 'RACK-C4'],
                ['desc' => 'Cable Duct 40x40mm PVC',        'uom' => 'BTG', 'min' => 20,  'max' => 200,  'loc' => 'RACK-C4'],
                ['desc' => 'Conduit PVC 3/4 inch x 3m',    'uom' => 'BTG', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C4'],
                ['desc' => 'Fuse 2A 250V Ceramic',          'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-C4'],
                ['desc' => 'Fuse 6A 250V Ceramic',          'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-C4'],
                ['desc' => 'Fuse 10A 250V Ceramic',         'uom' => 'PCS', 'min' => 50,  'max' => 500,  'loc' => 'RACK-C4'],
                ['desc' => 'Timer Relay 0-60s 220V',        'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C5'],
                ['desc' => 'Relay 24VDC SPDT',              'uom' => 'PCS', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C5'],
                ['desc' => 'Relay Socket DIN 8-pin',        'uom' => 'PCS', 'min' => 10,  'max' => 100,  'loc' => 'RACK-C5'],
                ['desc' => 'Digital Panel Meter Voltmeter', 'uom' => 'PCS', 'min' => 2,   'max' => 20,   'loc' => 'RACK-C5'],
                ['desc' => 'Current Transformer 50/5A',     'uom' => 'PCS', 'min' => 3,   'max' => 30,   'loc' => 'RACK-C5'],
                ['desc' => 'Power Supply 24VDC 10A',        'uom' => 'PCS', 'min' => 2,   'max' => 20,   'loc' => 'RACK-C5'],
            ],
            'CAT-MEC' => [
                ['desc' => 'Coupling Flexible Type Jaw 19mm', 'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-D1'],
                ['desc' => 'Coupling Flexible Type Jaw 28mm', 'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-D1'],
                ['desc' => 'V-Belt A40 Classical',           'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-D1'],
                ['desc' => 'V-Belt B48 Classical',           'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-D1'],
                ['desc' => 'V-Belt C60 Classical',           'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-D1'],
                ['desc' => 'Timing Belt T5 x 250',          'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-D2'],
                ['desc' => 'Chain Roller 08B-1 (10 feet)',  'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-D2'],
                ['desc' => 'Chain Roller 10B-1 (10 feet)',  'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-D2'],
                ['desc' => 'Sprocket Z25 T=8mm',            'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-D2'],
                ['desc' => 'Gear Spur M2 Z20',              'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-D2'],
                ['desc' => 'Key Steel 5x5x50mm',            'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-D3'],
                ['desc' => 'Key Steel 6x6x50mm',            'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-D3'],
                ['desc' => 'Key Steel 8x7x50mm',            'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-D3'],
                ['desc' => 'Locking Assembly OD38 x ID20',  'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-D3'],
                ['desc' => 'Shaft Collar 20mm Clamp Type', 'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-D3'],
                ['desc' => 'Shim Plate 1mm x 100x100mm',   'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-D4'],
                ['desc' => 'Shim Plate 3mm x 100x100mm',   'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-D4'],
                ['desc' => 'Grease Nipple 1/8 NPT',         'uom' => 'PCS', 'min' => 50,  'max' => 500, 'loc' => 'RACK-D4'],
                ['desc' => 'Spring Compression 30x80mm',    'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-D4'],
                ['desc' => 'O-Ring NBR 50x3mm',             'uom' => 'PCS', 'min' => 50,  'max' => 500, 'loc' => 'RACK-D4'],
                ['desc' => 'Oil Level Sight Glass 3/4 inch', 'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-D5'],
                ['desc' => 'Gearbox Reducer 1:20 IEC90',   'uom' => 'PCS', 'min' => 1,   'max' => 10,  'loc' => 'RACK-D5'],
                ['desc' => 'Gearbox Reducer 1:50 IEC100',  'uom' => 'PCS', 'min' => 1,   'max' => 10,  'loc' => 'RACK-D5'],
                ['desc' => 'Compression Spring D25x80mm',   'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-D5'],
                ['desc' => 'Snap Ring External 25mm',       'uom' => 'PCS', 'min' => 50,  'max' => 500, 'loc' => 'RACK-D5'],
            ],
            'CAT-PIP' => [
                ['desc' => 'Pipe CS ASTM A53 1 inch SCH40 (6m)', 'uom' => 'BTG', 'min' => 5, 'max' => 50, 'loc' => 'PIPE-YARD'],
                ['desc' => 'Pipe CS ASTM A53 2 inch SCH40 (6m)', 'uom' => 'BTG', 'min' => 5, 'max' => 50, 'loc' => 'PIPE-YARD'],
                ['desc' => 'Pipe CS ASTM A53 3 inch SCH40 (6m)', 'uom' => 'BTG', 'min' => 3, 'max' => 30, 'loc' => 'PIPE-YARD'],
                ['desc' => 'Pipe CS ASTM A53 4 inch SCH40 (6m)', 'uom' => 'BTG', 'min' => 3, 'max' => 30, 'loc' => 'PIPE-YARD'],
                ['desc' => 'Pipe SS316 1/2 inch SCH10 (6m)',  'uom' => 'BTG', 'min' => 3,   'max' => 30,  'loc' => 'PIPE-YARD'],
                ['desc' => 'Pipe SS316 1 inch SCH10 (6m)',    'uom' => 'BTG', 'min' => 3,   'max' => 30,  'loc' => 'PIPE-YARD'],
                ['desc' => 'Elbow 90° CS 2 inch SCH40',       'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-E1'],
                ['desc' => 'Elbow 90° CS 3 inch SCH40',       'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-E1'],
                ['desc' => 'Elbow 45° CS 2 inch SCH40',       'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E1'],
                ['desc' => 'Tee Equal CS 2 inch SCH40',       'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E1'],
                ['desc' => 'Tee Reducing CS 2x1 inch SCH40', 'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E1'],
                ['desc' => 'Reducer Concentric 3x2 inch',     'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E2'],
                ['desc' => 'Reducer Eccentric 3x2 inch',      'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E2'],
                ['desc' => 'Flange WN 2 inch ANSI 150#',      'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E2'],
                ['desc' => 'Flange SLIP-ON 2 inch ANSI 150#', 'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E2'],
                ['desc' => 'Flange Blind 2 inch ANSI 150#',   'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-E2'],
                ['desc' => 'Pipe Cap CS 1 inch',               'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-E3'],
                ['desc' => 'Pipe Cap CS 2 inch',               'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-E3'],
                ['desc' => 'Nipple CS 1/2 inch x 100mm',      'uom' => 'PCS', 'min' => 30,  'max' => 300, 'loc' => 'RACK-E3'],
                ['desc' => 'Nipple CS 3/4 inch x 100mm',      'uom' => 'PCS', 'min' => 30,  'max' => 300, 'loc' => 'RACK-E3'],
                ['desc' => 'Socket CS 1/2 inch',               'uom' => 'PCS', 'min' => 50,  'max' => 500, 'loc' => 'RACK-E3'],
                ['desc' => 'Hydraulic Hose 1/4 inch x 1m',    'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E4'],
                ['desc' => 'Hydraulic Hose 3/8 inch x 1m',    'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-E4'],
                ['desc' => 'Hydraulic Fitting BSP 1/4 inch',  'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-E4'],
                ['desc' => 'Pipe Clamp CS 2 inch',             'uom' => 'PCS', 'min' => 50,  'max' => 500, 'loc' => 'RACK-E4'],
            ],
            'CAT-VLV' => [
                ['desc' => 'Ball Valve 1/2 inch SS316 PN40',  'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-F1'],
                ['desc' => 'Ball Valve 1 inch SS316 PN40',    'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-F1'],
                ['desc' => 'Ball Valve 2 inch SS316 PN40',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F1'],
                ['desc' => 'Ball Valve 3 inch CS PN16',       'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F1'],
                ['desc' => 'Gate Valve 2 inch CS PN16',       'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F1'],
                ['desc' => 'Gate Valve 4 inch CS PN16',       'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-F2'],
                ['desc' => 'Globe Valve 1 inch CS PN16',      'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F2'],
                ['desc' => 'Globe Valve 2 inch CS PN16',      'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F2'],
                ['desc' => 'Check Valve 2 inch Swing Type',   'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F2'],
                ['desc' => 'Check Valve 3 inch Lift Type',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F2'],
                ['desc' => 'Butterfly Valve 4 inch PN16',     'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-F3'],
                ['desc' => 'Butterfly Valve 6 inch PN16',     'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-F3'],
                ['desc' => 'Needle Valve 1/4 inch SS316',     'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-F3'],
                ['desc' => 'Safety Relief Valve 1 inch 10bar', 'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-F3'],
                ['desc' => 'Pressure Control Valve 1/2 inch', 'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-F3'],
                ['desc' => 'Solenoid Valve 1/2 inch 24VDC',  'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F4'],
                ['desc' => 'Solenoid Valve 1 inch 220VAC',   'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F4'],
                ['desc' => 'Y-Strainer 1/2 inch SS316',       'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F4'],
                ['desc' => 'Y-Strainer 2 inch CS',            'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-F4'],
                ['desc' => 'Globe Valve 3/4 inch Bronze',     'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-F4'],
            ],
            'CAT-LUB' => [
                ['desc' => 'Mobil DTE 25 Hydraulic Oil (20L)', 'uom' => 'DRUM', 'min' => 3, 'max' => 30, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Shell Tellus 46 Hydraulic Oil (20L)', 'uom' => 'DRUM', 'min' => 3, 'max' => 30, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Mobil SHC 320 Gear Oil (20L)',    'uom' => 'DRUM', 'min' => 2,   'max' => 20,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Shell Omala 320 Gear Oil (20L)',  'uom' => 'DRUM', 'min' => 2,   'max' => 20,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Mobil Grease XHP 222 (16kg)',     'uom' => 'KG',   'min' => 5,   'max' => 50,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Shell Alvania EP2 Grease (18kg)', 'uom' => 'KG',   'min' => 5,   'max' => 50,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Castrol Molub-Alloy 930 (1kg)',   'uom' => 'KG',   'min' => 5,   'max' => 50,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Mobil Rarus 427 Compressor Oil (20L)', 'uom' => 'DRUM', 'min' => 2, 'max' => 20, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Turbine Oil T46 (20L)',           'uom' => 'DRUM', 'min' => 2,   'max' => 20,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Anti-Seize Compound 500g',        'uom' => 'KG',   'min' => 5,   'max' => 50,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Rust Inhibitor Spray 400ml',      'uom' => 'CAN',  'min' => 10,  'max' => 100, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Thread Sealant PTFE Tape 25m',   'uom' => 'ROL',  'min' => 20,  'max' => 200, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Lithium Grease Multipurpose 1kg', 'uom' => 'KG',   'min' => 10,  'max' => 100, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Chain Lubricant Spray 400ml',     'uom' => 'CAN',  'min' => 10,  'max' => 100, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Penetrating Oil WD-40 450ml',     'uom' => 'CAN',  'min' => 20,  'max' => 200, 'loc' => 'CHEM-STORE'],
            ],
            'CAT-SAF' => [
                ['desc' => 'Safety Helmet Yellow MSA V-Gard',  'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-G1'],
                ['desc' => 'Safety Helmet White MSA V-Gard',   'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-G1'],
                ['desc' => 'Safety Glasses Clear Lens',        'uom' => 'PCS', 'min' => 30,  'max' => 300, 'loc' => 'RACK-G1'],
                ['desc' => 'Safety Glasses Dark Lens',         'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-G1'],
                ['desc' => 'Safety Gloves Cut Resistant L',    'uom' => 'PCS', 'min' => 30,  'max' => 300, 'loc' => 'RACK-G2'],
                ['desc' => 'Safety Gloves Cut Resistant M',    'uom' => 'PCS', 'min' => 30,  'max' => 300, 'loc' => 'RACK-G2'],
                ['desc' => 'Safety Gloves Chemical Resistant', 'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-G2'],
                ['desc' => 'Safety Shoes Steel Toe Size 42',   'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-G2'],
                ['desc' => 'Safety Shoes Steel Toe Size 43',   'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-G2'],
                ['desc' => 'Safety Vest Reflective Orange',    'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-G3'],
                ['desc' => 'Safety Harness Full Body Type',    'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-G3'],
                ['desc' => 'Lanyard Energy Absorber 1.8m',     'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-G3'],
                ['desc' => 'Ear Plug Disposable 33dB (200 pair)', 'uom' => 'BOX', 'min' => 5, 'max' => 50, 'loc' => 'RACK-G3'],
                ['desc' => 'Respirator Half Mask 3M 6200',    'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-G4'],
                ['desc' => 'Cartridge Filter 3M 6001 Organic', 'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-G4'],
                ['desc' => 'Fire Extinguisher CO2 5kg',        'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-G4'],
                ['desc' => 'Fire Extinguisher ABC Powder 6kg', 'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-G4'],
                ['desc' => 'Caution Tape Yellow 500m',         'uom' => 'ROL', 'min' => 5,   'max' => 50,  'loc' => 'RACK-G4'],
                ['desc' => 'Safety Cone 45cm Orange',          'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-G5'],
                ['desc' => 'Lock Out Tag Out Set',             'uom' => 'SET', 'min' => 3,   'max' => 30,  'loc' => 'RACK-G5'],
            ],
            'CAT-HND' => [
                ['desc' => 'Combination Wrench 10mm',          'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H1'],
                ['desc' => 'Combination Wrench 12mm',          'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H1'],
                ['desc' => 'Combination Wrench 17mm',          'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H1'],
                ['desc' => 'Adjustable Wrench 12 inch',        'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H1'],
                ['desc' => 'Pipe Wrench 14 inch',              'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H1'],
                ['desc' => 'Torque Wrench 1/2 inch 25-150Nm', 'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-H2'],
                ['desc' => 'Allen Key Set 1.5-10mm',           'uom' => 'SET', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H2'],
                ['desc' => 'Screwdriver Set Flat/Cross',       'uom' => 'SET', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H2'],
                ['desc' => 'Hammer Claw 16oz',                 'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H2'],
                ['desc' => 'Hammer Rubber 1kg',                'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H2'],
                ['desc' => 'Chisel Flat 1/2 inch',             'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H3'],
                ['desc' => 'File Set Half Round 250mm',        'uom' => 'SET', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H3'],
                ['desc' => 'Hacksaw Frame with Blade',         'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H3'],
                ['desc' => 'Hacksaw Blade 300mm 24T (10pcs)', 'uom' => 'PKT', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H3'],
                ['desc' => 'Plier Combination 8 inch',         'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H3'],
                ['desc' => 'Plier Long Nose 6 inch',           'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H4'],
                ['desc' => 'Wire Cutter 6 inch',               'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-H4'],
                ['desc' => 'Stripper Wire 10-22AWG',           'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-H4'],
                ['desc' => 'Crimping Tool Coax RG6',           'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-H4'],
                ['desc' => 'Multimeter Digital Fluke 117',     'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-H4'],
            ],
            'CAT-PWR' => [
                ['desc' => 'Drill Cordless 18V Makita DHP458', 'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-I1'],
                ['desc' => 'Drill Bits Set HSS 1-13mm',        'uom' => 'SET', 'min' => 3,   'max' => 30,  'loc' => 'RACK-I1'],
                ['desc' => 'Angle Grinder 4 inch Makita 9523', 'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-I1'],
                ['desc' => 'Cutting Disc 4 inch x 1mm (25pcs)', 'uom' => 'BOX', 'min' => 5,   'max' => 50,  'loc' => 'RACK-I1'],
                ['desc' => 'Grinding Disc 4 inch x 6mm (25pcs)', 'uom' => 'BOX', 'min' => 5,   'max' => 50,  'loc' => 'RACK-I1'],
                ['desc' => 'Impact Wrench 1/2 inch Cordless',  'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-I2'],
                ['desc' => 'Jigsaw Cordless 18V',              'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I2'],
                ['desc' => 'Reciprocating Saw Cordless 18V',   'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I2'],
                ['desc' => 'Air Compressor 50L 1HP',           'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I2'],
                ['desc' => 'Welding Machine SMAW 250A',        'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I3'],
                ['desc' => 'Welding Electrode E6013 2.5mm (5kg)', 'uom' => 'PKT', 'min' => 5,  'max' => 50,  'loc' => 'RACK-I3'],
                ['desc' => 'Welding Electrode E7018 3.2mm (5kg)', 'uom' => 'PKT', 'min' => 3,  'max' => 30,  'loc' => 'RACK-I3'],
                ['desc' => 'Bench Grinder 6 inch',             'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I3'],
                ['desc' => 'Pipe Threading Machine 2 inch',    'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I3'],
                ['desc' => 'Magnetic Drill Press',             'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-I4'],
            ],
            'CAT-INS' => [
                ['desc' => 'Pressure Gauge 0-10 bar Glycerine', 'uom' => 'PCS', 'min' => 5,  'max' => 50,  'loc' => 'RACK-J1'],
                ['desc' => 'Pressure Gauge 0-16 bar Glycerine', 'uom' => 'PCS', 'min' => 5,  'max' => 50,  'loc' => 'RACK-J1'],
                ['desc' => 'Pressure Gauge 0-25 bar Dry',      'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-J1'],
                ['desc' => 'Temperature Gauge 0-100°C Bimetal', 'uom' => 'PCS', 'min' => 5,  'max' => 50,  'loc' => 'RACK-J1'],
                ['desc' => 'Temperature Gauge 0-200°C Bimetal', 'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-J1'],
                ['desc' => 'Thermocouple Type K 200mm',         'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-J2'],
                ['desc' => 'RTD PT100 3-wire 150mm',            'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-J2'],
                ['desc' => 'Flow Meter Turbine 1 inch',         'uom' => 'PCS', 'min' => 2,  'max' => 20,  'loc' => 'RACK-J2'],
                ['desc' => 'Level Switch Float Type',           'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-J2'],
                ['desc' => 'Pressure Transmitter 4-20mA',      'uom' => 'PCS', 'min' => 2,  'max' => 20,  'loc' => 'RACK-J3'],
                ['desc' => 'Temperature Transmitter 4-20mA',   'uom' => 'PCS', 'min' => 2,  'max' => 20,  'loc' => 'RACK-J3'],
                ['desc' => 'Vibration Sensor 4-20mA',          'uom' => 'PCS', 'min' => 2,  'max' => 20,  'loc' => 'RACK-J3'],
                ['desc' => 'Proximity Switch NPN 3-wire',       'uom' => 'PCS', 'min' => 10, 'max' => 100, 'loc' => 'RACK-J3'],
                ['desc' => 'Limit Switch Roller Type',          'uom' => 'PCS', 'min' => 10, 'max' => 100, 'loc' => 'RACK-J4'],
                ['desc' => 'Encoder Rotary 100ppr',             'uom' => 'PCS', 'min' => 2,  'max' => 20,  'loc' => 'RACK-J4'],
            ],
            'CAT-CBL' => [
                ['desc' => 'NYY Cable 4x1.5mm2 (100m)',        'uom' => 'ROL', 'min' => 3,   'max' => 30,  'loc' => 'RACK-K1'],
                ['desc' => 'NYY Cable 4x2.5mm2 (100m)',        'uom' => 'ROL', 'min' => 3,   'max' => 30,  'loc' => 'RACK-K1'],
                ['desc' => 'NYY Cable 4x4mm2 (100m)',          'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-K1'],
                ['desc' => 'NYY Cable 4x6mm2 (100m)',          'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-K1'],
                ['desc' => 'NYFGbY Cable 3x16mm2 (100m)',      'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-K2'],
                ['desc' => 'NYFGbY Cable 3x35mm2 (100m)',      'uom' => 'ROL', 'min' => 1,   'max' => 10,  'loc' => 'RACK-K2'],
                ['desc' => 'Control Cable 12x1.5mm2 (100m)',   'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-K2'],
                ['desc' => 'Instrument Cable Pair 2x0.75mm2',  'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-K3'],
                ['desc' => 'Coaxial Cable RG6 (100m)',         'uom' => 'ROL', 'min' => 2,   'max' => 20,  'loc' => 'RACK-K3'],
                ['desc' => 'Ethernet Cable CAT6 UTP (100m)',   'uom' => 'ROL', 'min' => 3,   'max' => 30,  'loc' => 'RACK-K3'],
                ['desc' => 'Cable Lug Copper 10mm2 M6',        'uom' => 'PCS', 'min' => 50,  'max' => 500, 'loc' => 'RACK-K3'],
                ['desc' => 'Cable Lug Copper 25mm2 M8',        'uom' => 'PCS', 'min' => 30,  'max' => 300, 'loc' => 'RACK-K3'],
                ['desc' => 'Cable Tie 4x200mm (100pcs)',        'uom' => 'PKT', 'min' => 10,  'max' => 100, 'loc' => 'RACK-K4'],
                ['desc' => 'Cable Tie 8x400mm (100pcs)',        'uom' => 'PKT', 'min' => 10,  'max' => 100, 'loc' => 'RACK-K4'],
                ['desc' => 'Heat Shrink Tube 10mm x 1m',       'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-K4'],
            ],
            'CAT-PMP' => [
                ['desc' => 'Centrifugal Pump Impeller 6 inch', 'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-L1'],
                ['desc' => 'Centrifugal Pump Casing CS',       'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-L1'],
                ['desc' => 'Pump Shaft SS316 25mm x 300mm',   'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-L1'],
                ['desc' => 'Pump Wear Ring SS316',             'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-L1'],
                ['desc' => 'Pump Coupling Spacer',             'uom' => 'PCS', 'min' => 2,   'max' => 20,  'loc' => 'RACK-L2'],
                ['desc' => 'Submersible Pump Float Switch',    'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-L2'],
                ['desc' => 'Pump Repair Kit Mechanical Seal',  'uom' => 'SET', 'min' => 3,   'max' => 30,  'loc' => 'RACK-L2'],
                ['desc' => 'Diaphragm Pump Air Section',       'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-L2'],
                ['desc' => 'Check Valve Pump Foot 2 inch',     'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-L3'],
                ['desc' => 'Pump Pressure Switch 1-12 bar',   'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-L3'],
            ],
            'CAT-MTR' => [
                ['desc' => 'Electric Motor 3-Phase 5.5kW IE3', 'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M1'],
                ['desc' => 'Electric Motor 3-Phase 11kW IE3',  'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M1'],
                ['desc' => 'Electric Motor 3-Phase 22kW IE3',  'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M1'],
                ['desc' => 'Motor Fan Blade Assembly',          'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-M2'],
                ['desc' => 'Motor Terminal Box Cover',          'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-M2'],
                ['desc' => 'Motor Rotor Assembly 15kW',        'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M2'],
                ['desc' => 'Motor Stator Winding Kit 7.5kW',  'uom' => 'SET', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M3'],
                ['desc' => 'VFD Drive 5.5kW 3-Phase 380V',    'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M3'],
                ['desc' => 'VFD Drive 11kW 3-Phase 380V',     'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M3'],
                ['desc' => 'Soft Starter 22kW 380V',           'uom' => 'PCS', 'min' => 1,   'max' => 5,   'loc' => 'RACK-M3'],
            ],
            'CAT-FLT' => [
                ['desc' => 'Oil Filter Spin-on HF35486',       'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-N1'],
                ['desc' => 'Hydraulic Filter Element 25µm',    'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-N1'],
                ['desc' => 'Air Filter Element Engine',         'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-N1'],
                ['desc' => 'Compressed Air Filter 0.01µm',     'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-N1'],
                ['desc' => 'Bag Filter 25µm PP 10 inch',       'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-N2'],
                ['desc' => 'Bag Filter 100µm PP 10 inch',      'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-N2'],
                ['desc' => 'Cartridge Filter 5µm PP 20 inch',  'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-N2'],
                ['desc' => 'Filter Drier Refrigeration 3/8 inch', 'uom' => 'PCS', 'min' => 5, 'max' => 50, 'loc' => 'RACK-N2'],
                ['desc' => 'Fuel Filter Diesel Engine',         'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-N3'],
                ['desc' => 'Water Filter Cartridge 5µm 10 inch', 'uom' => 'PCS', 'min' => 10, 'max' => 100, 'loc' => 'RACK-N3'],
            ],
            'CAT-SLR' => [
                ['desc' => 'Mechanical Seal Burgmann 25mm',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-O1'],
                ['desc' => 'Mechanical Seal Burgmann 30mm',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-O1'],
                ['desc' => 'Mechanical Seal Burgmann 40mm',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-O1'],
                ['desc' => 'Lip Seal NBR 25x40x7mm',          'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-O2'],
                ['desc' => 'Lip Seal NBR 40x60x10mm',         'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-O2'],
                ['desc' => 'Piston Seal NBR 50mm',            'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-O2'],
                ['desc' => 'V-Ring Seal NBR 40mm',             'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-O3'],
                ['desc' => 'PTFE Seal Ring 25mm',              'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-O3'],
                ['desc' => 'Packing Gland PTFE 1/2 inch',     'uom' => 'MTR', 'min' => 5,   'max' => 50,  'loc' => 'RACK-O3'],
                ['desc' => 'Rotary Seal TC 35x52x7mm',         'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-O3'],
            ],
            'CAT-GSK' => [
                ['desc' => 'Gasket Spiral Wound 1 inch ANSI 150#', 'uom' => 'PCS', 'min' => 10, 'max' => 100, 'loc' => 'RACK-P1'],
                ['desc' => 'Gasket Spiral Wound 2 inch ANSI 150#', 'uom' => 'PCS', 'min' => 10, 'max' => 100, 'loc' => 'RACK-P1'],
                ['desc' => 'Gasket Spiral Wound 3 inch ANSI 150#', 'uom' => 'PCS', 'min' => 5,  'max' => 50,  'loc' => 'RACK-P1'],
                ['desc' => 'Gasket Ring Joint Oval 2 inch',   'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-P2'],
                ['desc' => 'Gasket Klingersil C4400 1mm',     'uom' => 'SHT', 'min' => 5,   'max' => 50,  'loc' => 'RACK-P2'],
                ['desc' => 'Gasket Rubber NBR 2mm Sheet',     'uom' => 'SHT', 'min' => 5,   'max' => 50,  'loc' => 'RACK-P2'],
                ['desc' => 'Gasket Rubber EPDM 3mm Sheet',    'uom' => 'SHT', 'min' => 3,   'max' => 30,  'loc' => 'RACK-P3'],
                ['desc' => 'Gasket Ring Joint Octagonal 3 inch', 'uom' => 'PCS', 'min' => 3,  'max' => 30,  'loc' => 'RACK-P3'],
                ['desc' => 'Flange Gasket Full Face 1 inch',  'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-P3'],
                ['desc' => 'Flange Gasket Full Face 2 inch',  'uom' => 'PCS', 'min' => 20,  'max' => 200, 'loc' => 'RACK-P3'],
            ],
            'CAT-WRK' => [
                ['desc' => 'Ratchet Tie Down Strap 5T x 10m', 'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-Q1'],
                ['desc' => 'Chain Block 3T x 3m',              'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-Q1'],
                ['desc' => 'Wire Rope Sling 1 inch x 3m 6-leg', 'uom' => 'PCS', 'min' => 3,  'max' => 30, 'loc' => 'RACK-Q1'],
                ['desc' => 'Shackle Bow Type 3/4 inch 2T',    'uom' => 'PCS', 'min' => 10,  'max' => 100, 'loc' => 'RACK-Q2'],
                ['desc' => 'Workbench Vise 4 inch',            'uom' => 'PCS', 'min' => 2,   'max' => 10,  'loc' => 'RACK-Q2'],
                ['desc' => 'Measuring Tape 5m Stanley',        'uom' => 'PCS', 'min' => 5,   'max' => 50,  'loc' => 'RACK-Q2'],
                ['desc' => 'Spirit Level 24 inch',             'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-Q2'],
                ['desc' => 'Steel Ruler 1m',                   'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-Q3'],
                ['desc' => 'Thread Gauge Metric M1.6-M16',     'uom' => 'SET', 'min' => 2,   'max' => 10,  'loc' => 'RACK-Q3'],
                ['desc' => 'Vernier Caliper Digital 150mm',    'uom' => 'PCS', 'min' => 3,   'max' => 30,  'loc' => 'RACK-Q3'],
            ],
            'CAT-CLN' => [
                ['desc' => 'Industrial Degreaser 20L',         'uom' => 'DRUM', 'min' => 3,  'max' => 30,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Solvent Cleaner IPA 99% 20L',     'uom' => 'DRUM', 'min' => 2,  'max' => 20,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Detergent Industrial Heavy Duty 20L', 'uom' => 'DRUM', 'min' => 5,  'max' => 50, 'loc' => 'CHEM-STORE'],
                ['desc' => 'Rust Remover Acid 5L',             'uom' => 'CAN',  'min' => 5,  'max' => 50,  'loc' => 'CHEM-STORE'],
                ['desc' => 'Wiper Cloth Industrial (50pcs)',   'uom' => 'PKT',  'min' => 20, 'max' => 200, 'loc' => 'RACK-R1'],
                ['desc' => 'Absorbent Pad Oil Spill (100pcs)', 'uom' => 'PKT',  'min' => 5,  'max' => 50,  'loc' => 'RACK-R1'],
                ['desc' => 'Absorbent Boom Universal 3m',      'uom' => 'PCS',  'min' => 5,  'max' => 50,  'loc' => 'RACK-R1'],
                ['desc' => 'Broom Industrial Heavy Duty',      'uom' => 'PCS',  'min' => 5,  'max' => 50,  'loc' => 'RACK-R1'],
                ['desc' => 'Mop Floor Industrial',             'uom' => 'PCS',  'min' => 5,  'max' => 50,  'loc' => 'RACK-R1'],
                ['desc' => 'Waste Drum 200L Plastic',          'uom' => 'PCS',  'min' => 3,  'max' => 30,  'loc' => 'RACK-R1'],
            ],
            'CAT-GEN' => [
                ['desc' => 'Cable Identification Marker',       'uom' => 'SET',  'min' => 10, 'max' => 100, 'loc' => 'RACK-S1'],
                ['desc' => 'Zip Lock Bag A4 Size (100pcs)',    'uom' => 'PKT',  'min' => 5,  'max' => 50,  'loc' => 'RACK-S1'],
                ['desc' => 'Permanent Marker Black (12pcs)',   'uom' => 'BOX',  'min' => 5,  'max' => 50,  'loc' => 'RACK-S1'],
                ['desc' => 'Label Sticker White A4 (10pcs)',   'uom' => 'PKT',  'min' => 5,  'max' => 50,  'loc' => 'RACK-S1'],
                ['desc' => 'Padlock Brass 40mm',               'uom' => 'PCS',  'min' => 10, 'max' => 100, 'loc' => 'RACK-S2'],
                ['desc' => 'Padlock Steel 50mm',               'uom' => 'PCS',  'min' => 10, 'max' => 100, 'loc' => 'RACK-S2'],
                ['desc' => 'Pallet Plastic 1200x1000mm',       'uom' => 'PCS',  'min' => 5,  'max' => 50,  'loc' => 'RACK-S2'],
                ['desc' => 'Storage Bin Plastic 400x300mm',   'uom' => 'PCS',  'min' => 10, 'max' => 100, 'loc' => 'RACK-S2'],
                ['desc' => 'Silica Gel Sachet 50g (100pcs)',  'uom' => 'PKT',  'min' => 10, 'max' => 100, 'loc' => 'RACK-S3'],
                ['desc' => 'Bubble Wrap 50cm x 50m',          'uom' => 'ROL',  'min' => 5,  'max' => 50,  'loc' => 'RACK-S3'],
                ['desc' => 'Packing Tape 48mm x 100m',        'uom' => 'ROL',  'min' => 10, 'max' => 100, 'loc' => 'RACK-S3'],
                ['desc' => 'Masking Tape 24mm x 50m',         'uom' => 'ROL',  'min' => 20, 'max' => 200, 'loc' => 'RACK-S3'],
            ],
        ];

        // Flatten all templates into a materials array
        $materials = [];
        $materialIndex = 1;
        $plantCount = count($plantIds);
        $catIndex = 0;

        foreach ($templates as $catCode => $items) {
            $categoryId = $categoryMap[$catCode] ?? null;
            if (! $categoryId) {
                continue;
            }

            foreach ($items as $item) {
                $matNum = 'MAT-'.str_pad($materialIndex, 6, '0', STR_PAD_LEFT);
                $statusRand = ($materialIndex % 10 === 0) ? 'INACTIVE' : 'ACTIVE'; // ~10% INACTIVE

                $materials[] = [
                    'material_number' => $matNum,
                    'description' => $item['desc'],
                    'category_id' => $categoryId,
                    'uom' => $item['uom'],
                    'minimum_stock' => $item['min'],
                    'maximum_stock' => $item['max'],
                    'storage_location' => $item['loc'],
                    'plant_id' => $plantIds[$materialIndex % $plantCount],
                    'qr_code' => $matNum,
                    'status' => $statusRand,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];

                $materialIndex++;
            }
            $catIndex++;
        }

        // Limit materials array to 20 items total
        $materials = array_slice($materials, 0, 20);

        // Batch insert with updateOrInsert to be idempotent
        $chunks = array_chunk($materials, 200);
        foreach ($chunks as $chunk) {
            foreach ($chunk as $mat) {
                DB::table('materials')->updateOrInsert(
                    ['material_number' => $mat['material_number']],
                    $mat
                );
            }
        }

        $total = DB::table('materials')->count();
        $this->command->info("MaterialSeeder: {$total} materials seeded.");
    }
}
